# Generated by Django 4.1.13 on 2024-05-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(default='USER', max_length=100, primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='user_service.role'),
        ),
    ]
